name: 🐛 Bug Report / Nahlášení chyby
description: Report a bug that prevents you from using the project / Nahlaste chybu, která vám brání v používání projektu
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # 🇬🇧 Bug Report
        Thanks for reporting a bug! Please fill in the following information to help us resolve the issue quickly.

        # 🇨🇿 Nahlášení chyby
        Děkujeme za nahlášení chyby! Vyplňte prosím následující informace, které nám pomohou problém rychle vyřešit.

  - type: input
    id: version
    attributes:
      label: Version / Verze
      description: |
        🇬🇧 What version of the project are you using?
        🇨🇿 Jakou verzi projektu používáte?
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment / Prostředí
      description: |
        🇬🇧 On which environment did you encounter the bug?
        🇨🇿 Na jakém prostředí jste chybu zaznamenali?
      options:
        - Production
        - Development
        - Testing
        - Staging
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened? / Co se stalo?
      description: |
        🇬🇧 Describe the bug and the expected behavior.
        🇨🇿 Popište chybu a očekávané chování.
      placeholder: |
        🇬🇧 Description of the bug and what you expected to happen instead.
        🇨🇿 Popis chyby a co jste očekávali, že se stane místo toho.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce / Kroky k reprodukci
      description: |
        🇬🇧 How can we reproduce the bug?
        🇨🇿 Jak můžeme chybu reprodukovat?
      placeholder: |
        🇬🇧 For example:
        1. Open...
        2. Click on...
        3. Scroll down to...
        4. See error...

        🇨🇿 Například:
        1. Otevřít...
        2. Kliknout na...
        3. Procházet dolů na...
        4. Vidět chybu...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / Relevantní logy
      description: |
        🇬🇧 Please include any relevant logs or error messages if available.
        🇨🇿 Vložte prosím relevantní logy nebo chybové zprávy, pokud jsou k dispozici.
      render: shell
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers / Prohlížeče
      description: |
        🇬🇧 If relevant, which browsers have you seen the issue on?
        🇨🇿 Pokud je to relevantní, v jakých prohlížečích jste chybu zaznamenali?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Brave
        - Jiný / Other
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System / Operační systém
      description: |
        🇬🇧 On which operating system did you encounter the bug?
        🇨🇿 Na jakém operačním systému jste chybu zaznamenali?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Jiný / Other
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context / Dodatečný kontext
      description: |
        🇬🇧 Any additional information that might be relevant to this issue.
        🇨🇿 Jakékoliv další informace, které by mohly být relevantní pro tento problém.
      placeholder: |
        🇬🇧 Add any other context or screenshots if possible.
        🇨🇿 Přidejte jakýkoliv další kontext nebo snímky obrazovky, pokud je to možné.
    validations:
      required: false

