name: 💡 Feature Request / Návrh nové funkce
description: Suggest a new feature or enhancement / Navrhnout novou funkci nebo vylepšení
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # 🇬🇧 Feature Request
        Thank you for your suggestion! Your ideas are important to us. Please fill in the following information to help us better understand your proposal.

        # 🇨🇿 Návrh nové funkce
        Děkujeme za váš návrh! Vaše nápady jsou pro nás důležité. Vyplňte prosím následující informace, které nám pomohou lépe pochopit váš návrh.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? / Je váš návrh spojen s nějakým problémem?
      description: |
        🇬🇧 A clear and concise description of the problem. Ex. I'm always frustrated when [...]
        🇨🇿 Jasný a stručný popis problému. Např. Vždy jsem frustrován, když [...]
      placeholder: |
        🇬🇧 Describe the problem you'd like to solve.
        🇨🇿 Popište problém, který chcete vyřešit.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: What solution would you like? / Jaké řešení byste chtěli?
      description: |
        🇬🇧 A clear and concise description of what you want to happen.
        🇨🇿 Jasný a stručný popis toho, co chcete, aby se stalo.
      placeholder: |
        🇬🇧 Describe the solution you'd like to see.
        🇨🇿 Popište řešení, které si představujete.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered? / Jaké alternativy jste zvažovali?
      description: |
        🇬🇧 A clear and concise description of any alternative solutions or features you've considered.
        🇨🇿 Jasný a stručný popis jakýchkoli alternativních řešení nebo funkcí, které jste zvažovali.
      placeholder: |
        🇬🇧 Describe alternative solutions you've considered.
        🇨🇿 Popište alternativní řešení, která jste zvažovali.
    validations:
      required: false

  - type: dropdown
    id: importance
    attributes:
      label: Importance / Důležitost
      description: |
        🇬🇧 How important is this feature to you?
        🇨🇿 Jak důležitá je pro vás tato funkce?
      options:
        - Critical / Kritická
        - High / Vysoká
        - Medium / Střední
        - Low / Nízká
    validations:
      required: false

  - type: dropdown
    id: user-impact
    attributes:
      label: User Impact / Dopad na uživatele
      description: |
        🇬🇧 How many users do you think this feature would affect?
        🇨🇿 Kolik uživatelů by podle vás tato funkce ovlivnila?
      options:
        - Most users / Většinu uživatelů
        - Many users / Mnoho uživatelů
        - Some users / Některé uživatele
        - Just a few users / Jen pár uživatelů
        - Not sure / Nejsem si jistý/á
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context / Dodatečný kontext
      description: |
        🇬🇧 Add any other context or screenshots about the feature request here.
        🇨🇿 Přidejte jakýkoli další kontext nebo snímky obrazovky o návrhu funkce zde.
      placeholder: |
        🇬🇧 Additional information, links, screenshots, or sketches that might help explain your proposal.
        🇨🇿 Další informace, odkazy, snímky obrazovky nebo náčrty, které by mohly pomoci vysvětlit váš návrh.
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution / Přispění
      description: |
        🇬🇧 Would you like to work on this feature?
        🇨🇿 Chtěli byste na této funkci pracovat?
      options:
        - Yes, I'd like to implement this feature / Ano, chtěl/a bych implementovat tuto funkci
        - I could help with part of the implementation / Mohl/a bych pomoci s částí implementace
        - No, I can't work on it, but I'd like to see it implemented / Ne, nemohu na tom pracovat, ale rád/a bych to viděl/a implementované
        - Other (please specify in the context section) / Jiné (prosím upřesněte v sekci kontext)
    validations:
      required: false

