name: Sync Files

on:
  # Spust칤 se p콏i zm캩n치ch v .github adres치콏i hlavn칤ho repozit치콏e
  push:
    branches:
      - main
      - master
    paths:
      - '.github/**'
  # Umo쮄갓je manu치ln칤 spu코t캩n칤
  workflow_dispatch:
    inputs:
      target_repos:
        description: 'C칤lov칠 repozit치콏e (odd캩len칠 캜치rkou) nebo "all" pro v코echny'
        required: false
        default: 'all'
        type: string
      sync_mode:
        description: 'Re쬴m synchronizace'
        required: true
        default: 'soft'
        type: choice
        options:
          - soft     # P콏eskakuje existuj칤c칤 soubory, kter칠 byly lok치ln캩 upraveny
          - default  # Aktualizuje soubory, ale zachov치v치 lok치ln칤 zm캩ny, pokud je .sync-config.json
          - force    # P콏episuje v코echny soubory (s v칳jimkou t캩ch v .sync-ignore)

jobs:
  prepare-targets:
    name: P콏ipravit seznam c칤lov칳ch repozit치콏콢
    runs-on: ubuntu-latest
    outputs:
      target_repos: ${{ steps.set-targets.outputs.repos }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get target repositories
        id: set-targets
        run: |
          if [[ "${{ github.event.inputs.target_repos }}" == "all" || "${{ github.event.inputs.target_repos }}" == "" ]]; then
            # Z칤sk치n칤 seznamu v코ech repozit치콏콢 organizace, krom캩 aktu치ln칤ho
            REPOS=$(gh repo list 21-000-000 --json name -q '.[].name' | grep -v "21-000-000")
            
            # V칳stup jako JSON pole
            REPOS_JSON=$(echo $REPOS | jq -R 'split(" ")')
            echo "repos=$REPOS_JSON" >> $GITHUB_OUTPUT
          else
            # P콏evod 캜치rkou odd캩len칠ho seznamu na JSON pole
            REPOS=$(echo "${{ github.event.inputs.target_repos }}" | tr ',' ' ')
            REPOS_JSON=$(echo $REPOS | jq -R 'split(" ")')
            echo "repos=$REPOS_JSON" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

  sync-files:
    name: Synchronizovat soubory
    needs: prepare-targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.prepare-targets.outputs.target_repos) }}
      fail-fast: false  # Pokra캜uje i kdy synchronizace jednoho repozit치콏e sel쬰
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source-repo
      
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: 21-000-000/${{ matrix.repo }}
          path: target-repo
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Create .sync-ignore if it doesn't exist
        run: |
          if [ ! -f "source-repo/.sync-ignore" ]; then
            # V칳choz칤 soubory, kter칠 nikdy nechceme synchronizovat
            cat > source-repo/.sync-ignore << EOF
            .git/
            .gitignore
            README.md
            LICENSE
            CODEOWNERS
            # Specifick칠 pro dan칳 repozit치콏
            .sync-ignore
            .sync-config.json
            EOF
          fi
      
      - name: Prepare sync configuration
        run: |
          # Zkontrolovat, zda existuje konfigura캜n칤 soubor v c칤lov칠m repozit치콏i
          SYNC_CONFIG="target-repo/.sync-config.json"
          SYNC_MODE="${{ github.event.inputs.sync_mode || 'default' }}"
          
          if [ ! -f "$SYNC_CONFIG" ]; then
            # Vytvo콏칤me v칳choz칤 konfiguraci
            echo '{
              "mode": "default",
              "files": {
                ".github/workflows/": { "protected": false },
                ".github/ISSUE_TEMPLATE/": { "protected": false },
                ".github/SECURITY.md": { "protected": false },
                ".github/CODE_OF_CONDUCT.md": { "protected": false },
                ".github/CONTRIBUTING.md": { "protected": false },
                ".github/PULL_REQUEST_TEMPLATE.md": { "protected": false },
                ".github/dependabot.yml": { "protected": false }
              }
            }' > "$SYNC_CONFIG"
          fi
          
          # Zvolit re쬴m synchronizace
          if [ "$SYNC_MODE" == "force" ]; then
            # V re쬴mu force p콏ep칤코eme konfiguraci
            python -c "
import json
with open('$SYNC_CONFIG', 'r') as f:
    config = json.load(f)
config['mode'] = 'force'
for key in config['files']:
    config['files'][key]['protected'] = False
with open('$SYNC_CONFIG', 'w') as f:
    json.dump(config, f, indent=2)
            "
          fi
      
      - name: Synchronize files
        id: sync
        run: |
          # Na캜칤st konfiguraci
          SYNC_CONFIG="target-repo/.sync-config.json"
          python -c "
import json, os, shutil, re
from pathlib import Path

# Na캜칤st konfiguraci
with open('$SYNC_CONFIG', 'r') as f:
    config = json.load(f)

# Na캜칤st .sync-ignore
ignore_patterns = []
if os.path.exists('source-repo/.sync-ignore'):
    with open('source-repo/.sync-ignore', 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                ignore_patterns.append(re.compile(line.replace('*', '.*')))

# Z칤skat seznam soubor콢 ke kop칤rov치n칤
files_to_copy = []
for file_pattern, options in config['files'].items():
    # P콏ev칠st pattern na regex
    pattern = file_pattern.replace('.', '\\.').replace('*', '.*')
    is_protected = options.get('protected', False)
    
    # Proch치zet zdrojov칳 adres치콏
    for root, dirs, files in os.walk('source-repo'):
        rel_path = os.path.relpath(root, 'source-repo')
        if rel_path == '.':
            rel_path = ''
        
        # Filtrovat podle ignore patterns
        should_ignore = False
        for ignore in ignore_patterns:
            if ignore.match(rel_path):
                should_ignore = True
                break
        if should_ignore:
            continue
        
        # Proch치zet soubory
        for file in files:
            src_file_path = os.path.join(rel_path, file)
            if any(ignore.match(src_file_path) for ignore in ignore_patterns):
                continue
            
            # Zkontrolovat, zda soubor odpov칤d치 vzoru
            if re.match(pattern, src_file_path):
                # P콏idat soubor do seznamu
                dst_file_path = os.path.join('target-repo', src_file_path)
                # Zkontrolovat, zda existuje v c칤li a je chr치n캩n칳
                if os.path.exists(dst_file_path) and is_protected and config['mode'] != 'force':
                    # P콏esko캜it chr치n캩n칳 soubor
                    print(f'Skipping protected file: {src_file_path}')
                    continue
                
                files_to_copy.append((
                    os.path.join('source-repo', src_file_path),
                    dst_file_path
                ))

# Kop칤rovat soubory
for src, dst in files_to_copy:
    # Vytvo콏it adres치콏e, pokud neexistuj칤
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    # Kop칤rovat soubor
    shutil.copy2(src, dst)
    print(f'Copied: {src} -> {dst}')

# Vr치tit informaci o po캜tu zkop칤rovan칳ch soubor콢
print(f'::set-output name=copied_files::{len(files_to_copy)}')
          "
      
      - name: Create Pull Request
        if: steps.sync.outputs.copied_files != '0'
        run: |
          cd target-repo
          
          # Vytvo콏it v캩tev
          BRANCH_NAME="sync-files-$(date +%Y%m%d%H%M%S)"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b $BRANCH_NAME
          
          # Commitnout zm캩ny
          git add .
          git commit -m "游댃 Synchronizace soubor콢 z 21-000-000" -m "Automatick치 synchronizace soubor콢 z hlavn칤ho repozit치콏e organizace."
          git push origin $BRANCH_NAME
          
          # Vytvo콏it pull request
          gh pr create \
            --title "游댃 Synchronizace soubor콢 z 21-000-000" \
            --body "Tento Pull Request obsahuje automaticky synchronizovan칠 soubory z hlavn칤ho repozit치콏e organizace. Pros칤m zkontrolujte zm캩ny p콏ed schv치len칤m." \
            --label "automated,maintenance" \
            --repo "21-000-000/${{ matrix.repo }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
      
      - name: Notify if nothing to sync
        if: steps.sync.outputs.copied_files == '0'
        run: echo "콯치dn칠 soubory nebyly synchronizov치ny pro ${{ matrix.repo }}. V코e je ji aktu치ln칤 nebo vylou캜eno."

  notify-completion:
    name: Ozn치mit dokon캜en칤
    needs: sync-files
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Create job summary
        run: |
          echo "# 游댃 Synchronizace soubor콢" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Synchronizace byla dokon캜ena pro n치sleduj칤c칤 repozit치콏e:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          for repo in ${{ join(fromJson(needs.prepare-targets.outputs.target_repos), ' ') }}; do
            echo "- [$repo](https://github.com/21-000-000/$repo)" >> $GITHUB_STEP_SUMMARY
          done
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Re쬴m synchronizace: ${{ github.event.inputs.sync_mode || 'default' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pro ka쬯칳 repozit치콏 byl vytvo콏en Pull Request, kter칳 mus칤 b칳t manu치ln캩 zkontrolov치n a schv치len." >> $GITHUB_STEP_SUMMARY

